main: ${main}
name: ${name}
version: ${version}
api-version: ${apiVersion}
authors:
  - ${authors}
website: ${website}
depend: [ "CraftLib" ]
description: ${description}
craftlib:
  libraries: ${libraries}